// AUTO-GENERATED by scripts/build-changelog.mjs.
// Do not edit by hand — rewrite on next push.
//
// To add an entry, include a line in a commit message:
//   CHANGELOG: 🔍 short title | optional longer sentence for the body
//
window.BUILT_IN_CHANGELOG = [
  {
    "id": "cl-43d5eb192c",
    "title": "add user-facing entries for the April 24 UX batch",
    "createdAt": "2026-04-24T19:53:39+03:00",
    "body": "add user-facing entries for the April 24 UX batch"
  },
  {
    "id": "cl-bde93b52d5",
    "title": "🏛 Страхування: правильний відсоток з першого дня",
    "createdAt": "2026-04-24T15:43:16+03:00",
    "body": "Перший внесок одразу починає приносити відсотки — «Зароблено» і «Дохід/день» тепер узгоджені."
  },
  {
    "id": "cl-bde93b52d5-1",
    "title": "💸 Податок для страхування",
    "createdAt": "2026-04-24T15:43:16+03:00",
    "body": "У формі портфеля можна вказати податок на страхове накопичення."
  },
  {
    "id": "cl-bde93b52d5-2",
    "title": "📈 Коректний графік приросту портфеля",
    "createdAt": "2026-04-24T15:43:16+03:00",
    "body": "Страхування враховує щорічні внески та індексацію, складний депозит рахується як компаунд, ОВДП — до фактичної суми погашення."
  }
];
