// AUTO-GENERATED by scripts/build-changelog.mjs.
// Do not edit by hand — rewrite on next push.
//
// To add an entry, include a line in a commit message:
//   CHANGELOG: 🔍 short title | optional longer sentence for the body
//
window.BUILT_IN_CHANGELOG = [];
